// generate-config.js
const fs = require('fs');
require('dotenv').config(); // This line reads your .env file

// Collect all API keys from the .env file
const apiKeys = [
  process.env.API_KEY_1,
  process.env.API_KEY_2,
  process.env.API_KEY_3,
  process.env.API_KEY_4,
  process.env.API_KEY_5,
].filter(Boolean); // .filter(Boolean) removes any keys that are not defined

// Create the JavaScript content for config.js
const configContent = `
// THIS FILE IS AUTO-GENERATED by generate-config.js
// DO NOT EDIT THIS FILE DIRECTLY.
// DO NOT COMMIT THIS FILE TO GIT.

const APP_CONFIG = {
  apiKeys: ${JSON.stringify(apiKeys, null, 2)}
};
`;

// Write the content to config.js
fs.writeFileSync('config.js', configContent.trim());

console.log('✅ Successfully generated config.js with your API keys.');